kind: ConfigMap
apiVersion: v1
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.x.255.200-172.x.255.250
